plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.protobuf) apply false
    alias(libs.plugins.versions)
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url = 'https://jitpack.io' }
    }
}

tasks.named("dependencyUpdates").configure {
    checkForGradleUpdate = false
    checkConstraints = false
    rejectVersionIf {
        def candidate = it.candidate
        def isNonStable = candidate.version.contains('alpha') || candidate.version.contains('beta') || candidate.version.contains('RC')
        return isNonStable
    }
    filterConfigurations { Configuration config ->
        config.name in ['implementation', 'api', 'runtimeOnly']
    }
}



